version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: student_marking_db
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
    volumes:
      - mongodb_data:/data/db
    networks:
      - student-marking-network

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: student_marking_backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://admin:password123@mongodb:27017/student_project_marking?authSource=admin
      - JWT_SECRET=your_super_secret_jwt_key_here_make_it_very_long_and_secure_for_production
      - JWT_EXPIRE=7d
      - PORT=5000
      - FRONTEND_URL=http://localhost:3000
    depends_on:
      - mongodb
    networks:
      - student-marking-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: student_marking_frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=http://localhost:5000
    depends_on:
      - backend
    networks:
      - student-marking-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  mongodb_data:
    driver: local

networks:
  student-marking-network:
    driver: bridge
